#!/bin/bash

# setup Rasperry Pi Temprature mechanism
# This modification adds the raspberry pi temperature to Victron Venus OS

# Venus files that need to be updated to activeate this package
qmlDir=/opt/victronenergy/gui/qml

packageLogFile="/var/log/RpiTemperature/current"

#### following lines incorporate SetupHelper utilities into this script
# Refer to the SetupHelper ReadMe file for details.
    
source "/data/SetupHelper/CommonResources"

#### end of lines to include SetupHelper

#### running manually and OK to proceed - prompt for input
if [ $scriptAction == 'NONE' ] ; then
    echo
    echo "The RpiTemperature adds the Rasperry Pi CPU Temperture"    
    echo
    standardActionPrompt
fi

#### here to do the actual work

if [ $scriptAction == 'INSTALL' ] ; then
    logMessage "++ Installing RpiTemperature"

    # updateActiveFile "$qmlDir/PageSettingsGeneral.qml"
    # updateActiveFile "$qmlDir/PageSettingsShutdown.qml"

    installService $packageName

    if $filesUpdated ; then
        restartGui=true
    fi
fi

# #### uninstalling - check scriptAction again
# if an install step failed package needs to be removed
if [ $scriptAction == 'UNINSTALL' ] ; then
    logMessage "++ Uninstalling RpiTemperature"

    # restoreActiveFile "$qmlDir/PageSettingsGeneral.qml"
    # restoreActiveFile "$qmlDir/PageSettingsShutdown.qml"
    removeService $packageName
fi

if $filesUpdated ; then
    restartGui=true
fi

# thats all folks - SCRIPT EXITS INSIDE THE FUNCTION
endScript
